import type { Category, Vendor, Product } from '../types'

// Mock Categories
export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Groceries',
    icon: '🛒',
  },
  {
    id: '2',
    name: 'Vegetables',
    icon: '🥬',
  },
  {
    id: '3',
    name: 'Fruits',
    icon: '🍎',
  },
  {
    id: '4',
    name: 'Medicines',
    icon: '💊',
  },
  {
    id: '5',
    name: 'Dairy',
    icon: '🥛',
  },
  {
    id: '6',
    name: 'Bakery',
    icon: '🍞',
  },
  {
    id: '7',
    name: 'Meat & Fish',
    icon: '🍗',
  },
  {
    id: '8',
    name: 'Electronics',
    icon: '📱',
  },
]

// Mock Vendors
export const mockVendors: Vendor[] = [
  {
    id: '1',
    userId: 'user1',
    businessName: 'Fresh Fruits Corner',
    businessType: 'Fruit Shop',
    verified: true,
    rating: 4.5,
    totalRatings: 234,
    address: {
      id: 'addr1',
      label: 'Shop',
      addressLine1: '123 Main Street',
      city: 'Mumbai',
      state: 'Maharashtra',
      postalCode: '400001',
      country: 'India',
      latitude: 19.0760,
      longitude: 72.8777,
    },
    businessHours: {
      monday: { open: '08:00', close: '20:00', isClosed: false },
      tuesday: { open: '08:00', close: '20:00', isClosed: false },
      wednesday: { open: '08:00', close: '20:00', isClosed: false },
      thursday: { open: '08:00', close: '20:00', isClosed: false },
      friday: { open: '08:00', close: '20:00', isClosed: false },
      saturday: { open: '08:00', close: '20:00', isClosed: false },
      sunday: { open: '09:00', close: '18:00', isClosed: false },
    },
    deliveryRadius: 5,
    deliveryFee: 20,
    minimumOrder: 100,
  },
  {
    id: '2',
    userId: 'user2',
    businessName: 'Green Vegetable Mart',
    businessType: 'Vegetable Shop',
    verified: true,
    rating: 4.8,
    totalRatings: 567,
    address: {
      id: 'addr2',
      label: 'Shop',
      addressLine1: '456 Market Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      postalCode: '400002',
      country: 'India',
      latitude: 19.0760,
      longitude: 72.8777,
    },
    businessHours: {
      monday: { open: '07:00', close: '21:00', isClosed: false },
      tuesday: { open: '07:00', close: '21:00', isClosed: false },
      wednesday: { open: '07:00', close: '21:00', isClosed: false },
      thursday: { open: '07:00', close: '21:00', isClosed: false },
      friday: { open: '07:00', close: '21:00', isClosed: false },
      saturday: { open: '07:00', close: '21:00', isClosed: false },
      sunday: { open: '07:00', close: '21:00', isClosed: false },
    },
    deliveryRadius: 3,
    deliveryFee: 15,
    minimumOrder: 150,
  },
  {
    id: '3',
    userId: 'user3',
    businessName: 'City Pharmacy',
    businessType: 'Pharmacy',
    verified: true,
    rating: 4.9,
    totalRatings: 892,
    address: {
      id: 'addr3',
      label: 'Shop',
      addressLine1: '789 Health Street',
      city: 'Mumbai',
      state: 'Maharashtra',
      postalCode: '400003',
      country: 'India',
      latitude: 19.0760,
      longitude: 72.8777,
    },
    businessHours: {
      monday: { open: '24/7', close: '24/7', isClosed: false },
      tuesday: { open: '24/7', close: '24/7', isClosed: false },
      wednesday: { open: '24/7', close: '24/7', isClosed: false },
      thursday: { open: '24/7', close: '24/7', isClosed: false },
      friday: { open: '24/7', close: '24/7', isClosed: false },
      saturday: { open: '24/7', close: '24/7', isClosed: false },
      sunday: { open: '24/7', close: '24/7', isClosed: false },
    },
    deliveryRadius: 10,
    deliveryFee: 30,
    minimumOrder: 50,
  },
  {
    id: '4',
    userId: 'user4',
    businessName: 'Tech Gadgets Hub',
    businessType: 'Electronics',
    verified: true,
    rating: 4.6,
    totalRatings: 342,
    address: {
      id: 'addr4',
      label: 'Store',
      addressLine1: '101 Tech Boulevard',
      city: 'Bangalore',
      state: 'Karnataka',
      postalCode: '560001',
      country: 'India',
      latitude: 12.9716,
      longitude: 77.5946,
    },
    businessHours: {
      monday: { open: '10:00', close: '21:00', isClosed: false },
      tuesday: { open: '10:00', close: '21:00', isClosed: false },
      wednesday: { open: '10:00', close: '21:00', isClosed: false },
      thursday: { open: '10:00', close: '21:00', isClosed: false },
      friday: { open: '10:00', close: '22:00', isClosed: false },
      saturday: { open: '10:00', close: '22:00', isClosed: false },
      sunday: { open: '11:00', close: '20:00', isClosed: false },
    },
    deliveryRadius: 7,
    deliveryFee: 50,
    minimumOrder: 500,
  },
  {
    id: '5',
    userId: 'user5',
    businessName: 'Golden Grain Bakery',
    businessType: 'Bakery',
    verified: true,
    rating: 4.7,
    totalRatings: 421,
    address: {
      id: 'addr5',
      label: 'Bakery',
      addressLine1: '202 Bread Street',
      city: 'Chennai',
      state: 'Tamil Nadu',
      postalCode: '600001',
      country: 'India',
      latitude: 13.0827,
      longitude: 80.2707,
    },
    businessHours: {
      monday: { open: '05:00', close: '20:00', isClosed: false },
      tuesday: { open: '05:00', close: '20:00', isClosed: false },
      wednesday: { open: '05:00', close: '20:00', isClosed: false },
      thursday: { open: '05:00', close: '20:00', isClosed: false },
      friday: { open: '05:00', close: '20:00', isClosed: false },
      saturday: { open: '05:00', close: '21:00', isClosed: false },
      sunday: { open: '06:00', close: '18:00', isClosed: false },
    },
    deliveryRadius: 4,
    deliveryFee: 25,
    minimumOrder: 75,
  },
  {
    id: '6',
    userId: 'user6',
    businessName: 'Organic Super Store',
    businessType: 'Grocery',
    verified: true,
    rating: 4.8,
    totalRatings: 654,
    address: {
      id: 'addr6',
      label: 'Supermarket',
      addressLine1: '303 Green Avenue',
      city: 'Hyderabad',
      state: 'Telangana',
      postalCode: '500001',
      country: 'India',
      latitude: 17.3850,
      longitude: 78.4867,
    },
    businessHours: {
      monday: { open: '07:00', close: '22:00', isClosed: false },
      tuesday: { open: '07:00', close: '22:00', isClosed: false },
      wednesday: { open: '07:00', close: '22:00', isClosed: false },
      thursday: { open: '07:00', close: '22:00', isClosed: false },
      friday: { open: '07:00', close: '23:00', isClosed: false },
      saturday: { open: '07:00', close: '23:00', isClosed: false },
      sunday: { open: '08:00', close: '21:00', isClosed: false },
    },
    deliveryRadius: 8,
    deliveryFee: 35,
    minimumOrder: 200,
  },
  {
    id: '7',
    userId: 'user7',
    businessName: 'Spice World Market',
    businessType: 'Grocery',
    verified: true,
    rating: 4.4,
    totalRatings: 187,
    address: {
      id: 'addr7',
      label: 'Market',
      addressLine1: '404 Spice Bazaar',
      city: 'Delhi',
      state: 'Delhi',
      postalCode: '110001',
      country: 'India',
      latitude: 28.7041,
      longitude: 77.1025,
    },
    businessHours: {
      monday: { open: '08:00', close: '21:00', isClosed: false },
      tuesday: { open: '08:00', close: '21:00', isClosed: false },
      wednesday: { open: '08:00', close: '21:00', isClosed: false },
      thursday: { open: '08:00', close: '21:00', isClosed: false },
      friday: { open: '08:00', close: '22:00', isClosed: false },
      saturday: { open: '08:00', close: '22:00', isClosed: false },
      sunday: { open: '09:00', close: '20:00', isClosed: false },
    },
    deliveryRadius: 6,
    deliveryFee: 20,
    minimumOrder: 120,
  },
  {
    id: '8',
    userId: 'user8',
    businessName: 'Fresh Meat Delight',
    businessType: 'Meat & Fish',
    verified: true,
    rating: 4.3,
    totalRatings: 298,
    address: {
      id: 'addr8',
      label: 'Shop',
      addressLine1: '505 Meat Street',
      city: 'Kolkata',
      state: 'West Bengal',
      postalCode: '700001',
      country: 'India',
      latitude: 22.5726,
      longitude: 88.3639,
    },
    businessHours: {
      monday: { open: '06:00', close: '20:00', isClosed: false },
      tuesday: { open: '06:00', close: '20:00', isClosed: false },
      wednesday: { open: '06:00', close: '20:00', isClosed: false },
      thursday: { open: '06:00', close: '20:00', isClosed: false },
      friday: { open: '06:00', close: '21:00', isClosed: false },
      saturday: { open: '06:00', close: '21:00', isClosed: false },
      sunday: { open: '07:00', close: '18:00', isClosed: false },
    },
    deliveryRadius: 5,
    deliveryFee: 40,
    minimumOrder: 300,
  },
  {
    id: '9',
    userId: 'user9',
    businessName: 'Dairy Fresh Express',
    businessType: 'Dairy',
    verified: true,
    rating: 4.9,
    totalRatings: 756,
    address: {
      id: 'addr9',
      label: 'Dairy',
      addressLine1: '606 Milk Road',
      city: 'Pune',
      state: 'Maharashtra',
      postalCode: '411001',
      country: 'India',
      latitude: 18.5204,
      longitude: 73.8567,
    },
    businessHours: {
      monday: { open: '05:00', close: '21:00', isClosed: false },
      tuesday: { open: '05:00', close: '21:00', isClosed: false },
      wednesday: { open: '05:00', close: '21:00', isClosed: false },
      thursday: { open: '05:00', close: '21:00', isClosed: false },
      friday: { open: '05:00', close: '21:00', isClosed: false },
      saturday: { open: '05:00', close: '21:00', isClosed: false },
      sunday: { open: '06:00', close: '20:00', isClosed: false },
    },
    deliveryRadius: 4,
    deliveryFee: 15,
    minimumOrder: 80,
  },
  {
    id: '10',
    userId: 'user10',
    businessName: 'Natural Medicine Center',
    businessType: 'Pharmacy',
    verified: true,
    rating: 4.7,
    totalRatings: 432,
    address: {
      id: 'addr10',
      label: 'Pharmacy',
      addressLine1: '707 Health Avenue',
      city: 'Ahmedabad',
      state: 'Gujarat',
      postalCode: '380001',
      country: 'India',
      latitude: 23.0225,
      longitude: 72.5714,
    },
    businessHours: {
      monday: { open: '08:00', close: '22:00', isClosed: false },
      tuesday: { open: '08:00', close: '22:00', isClosed: false },
      wednesday: { open: '08:00', close: '22:00', isClosed: false },
      thursday: { open: '08:00', close: '22:00', isClosed: false },
      friday: { open: '08:00', close: '23:00', isClosed: false },
      saturday: { open: '08:00', close: '23:00', isClosed: false },
      sunday: { open: '09:00', close: '21:00', isClosed: false },
    },
    deliveryRadius: 9,
    deliveryFee: 25,
    minimumOrder: 60,
  }
]

// Mock Products
// Create identical products across multiple vendors to demonstrate comparison
export const mockProducts: Product[] = [
  // Same product (Apples) from multiple vendors
  {
    id: '1',
    vendorId: '1',
    name: 'Fresh Apples',
    description: 'Premium quality Kashmir apples, crisp and sweet',
    price: 180,
    categoryId: '3',
    images: ['https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400'],
    stock: 50,
    unit: 'kg',
    weight: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '26',
    vendorId: '2',
    name: 'Fresh Apples',
    description: 'Crisp and juicy apples, great for snacking',
    price: 160,
    categoryId: '3',
    images: ['https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400'],
    stock: 30,
    unit: 'kg',
    weight: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '27',
    vendorId: '6',
    name: 'Fresh Apples',
    description: 'Organic apples from local farms',
    price: 200,
    categoryId: '3',
    images: ['https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400'],
    stock: 40,
    unit: 'kg',
    weight: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Same product (Bananas) from multiple vendors
  {
    id: '2',
    vendorId: '1',
    name: 'Bananas',
    description: 'Fresh yellow bananas, rich in potassium',
    price: 60,
    categoryId: '3',
    images: ['https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=400'],
    stock: 100,
    unit: 'dozen',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '28',
    vendorId: '2',
    name: 'Bananas',
    description: 'Ripe bananas, perfect for breakfast',
    price: 55,
    categoryId: '3',
    images: ['https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=400'],
    stock: 80,
    unit: 'dozen',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Same product (Tomatoes) from multiple vendors
  {
    id: '3',
    vendorId: '2',
    name: 'Tomatoes',
    description: 'Fresh farm tomatoes, perfect for cooking',
    price: 40,
    categoryId: '2',
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400'],
    stock: 75,
    unit: 'kg',
    weight: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '29',
    vendorId: '6',
    name: 'Tomatoes',
    description: 'Organic farm fresh tomatoes',
    price: 45,
    categoryId: '2',
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400'],
    stock: 60,
    unit: 'kg',
    weight: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Other products...
  {
    id: '4',
    vendorId: '2',
    name: 'Fresh Spinach',
    description: 'Organic spinach leaves, rich in iron',
    price: 35,
    categoryId: '2',
    images: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400'],
    stock: 30,
    unit: 'bunch',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    vendorId: '3',
    name: 'Paracetamol 500mg',
    description: 'Pain relief and fever reducer, 10 tablets',
    price: 25,
    categoryId: '4',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400'],
    stock: 200,
    unit: 'pack',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    vendorId: '4',
    name: 'Bluetooth Speaker',
    description: 'Waterproof portable Bluetooth speaker with 20W output',
    price: 2500,
    categoryId: '8',
    images: ['https://images.unsplash.com/photo-1606220588911-4a4260c1d7f6?w=400'],
    stock: 25,
    unit: 'pieces',
    weight: 0.5,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    vendorId: '5',
    name: 'Whole Wheat Bread',
    description: 'Freshly baked whole wheat bread, healthy and nutritious',
    price: 45,
    categoryId: '6',
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400'],
    stock: 60,
    unit: 'pack',
    weight: 0.4,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    vendorId: '6',
    name: 'Organic Brown Rice',
    description: 'Premium organic brown rice, unpolished and healthy',
    price: 120,
    categoryId: '1',
    images: ['https://images.unsplash.com/photo-1603486460800-9fd8de11a4ad?w=400'],
    stock: 100,
    unit: 'kg',
    weight: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '9',
    vendorId: '7',
    name: 'Turmeric Powder',
    description: 'Pure organic turmeric powder, anti-inflammatory properties',
    price: 80,
    categoryId: '1',
    images: ['https://images.unsplash.com/photo-1585747860718-2b5384ef940a?w=400'],
    stock: 80,
    unit: 'pack',
    weight: 0.2,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '10',
    vendorId: '8',
    name: 'Chicken Breast',
    description: 'Fresh chicken breast, boneless and skinless',
    price: 250,
    categoryId: '7',
    images: ['https://images.unsplash.com/photo-1603486460800-9fd8de11a4ad?w=400'],
    stock: 40,
    unit: 'kg',
    weight: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '11',
    vendorId: '9',
    name: 'Fresh Milk',
    description: 'Pasteurized fresh milk, packed daily',
    price: 60,
    categoryId: '5',
    images: ['https://images.unsplash.com/photo-1554995204-2e8b0bca7e0f?w=400'],
    stock: 150,
    unit: 'liters',
    weight: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '12',
    vendorId: '10',
    name: 'Vitamin C Tablets',
    description: 'Effervescent vitamin C tablets, 1000mg per tablet',
    price: 120,
    categoryId: '4',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400'],
    stock: 90,
    unit: 'pack',
    weight: 0.1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '13',
    vendorId: '1',
    name: 'Oranges',
    description: 'Sweet and juicy oranges from Nagpur',
    price: 100,
    categoryId: '3',
    images: ['https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=400'],
    stock: 65,
    unit: 'kg',
    weight: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '14',
    vendorId: '2',
    name: 'Carrots',
    description: 'Fresh organic carrots, rich in beta-carotene',
    price: 50,
    categoryId: '2',
    images: ['https://images.unsplash.com/photo-1586901533053-18dbcdbab0f0?w=400'],
    stock: 85,
    unit: 'kg',
    weight: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '15',
    vendorId: '3',
    name: 'Cough Syrup',
    description: 'Effective cough syrup for dry and wet cough',
    price: 95,
    categoryId: '4',
    images: ['https://images.unsplash.com/photo-1598204817638-75d5bed0e331?w=400'],
    stock: 75,
    unit: 'pack',
    weight: 0.15,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '16',
    vendorId: '4',
    name: 'Smartphone',
    description: 'Latest smartphone with 128GB storage and triple camera',
    price: 25000,
    categoryId: '8',
    images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400'],
    stock: 15,
    unit: 'pieces',
    weight: 0.2,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '17',
    vendorId: '5',
    name: 'Croissants',
    description: 'Buttery flaky croissants, freshly baked',
    price: 80,
    categoryId: '6',
    images: ['https://images.unsplash.com/photo-1614428775888-8ada2ac67b0c?w=400'],
    stock: 45,
    unit: 'pieces',
    weight: 0.1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '18',
    vendorId: '6',
    name: 'Quinoa',
    description: 'Organic quinoa, protein-rich grain',
    price: 350,
    categoryId: '1',
    images: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400'],
    stock: 35,
    unit: 'kg',
    weight: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '19',
    vendorId: '7',
    name: 'Red Chilli Powder',
    description: 'Hot red chilli powder, premium quality',
    price: 70,
    categoryId: '1',
    images: ['https://images.unsplash.com/photo-1585747860718-2b5384ef940a?w=400'],
    stock: 120,
    unit: 'pack',
    weight: 0.1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '20',
    vendorId: '8',
    name: 'Salmon Fillet',
    description: 'Fresh salmon fillet, omega-3 rich',
    price: 800,
    categoryId: '7',
    images: ['https://images.unsplash.com/photo-1622737133809-d917ad617346?w=400'],
    stock: 20,
    unit: 'kg',
    weight: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '21',
    vendorId: '9',
    name: 'Greek Yogurt',
    description: 'Creamy Greek yogurt, high protein content',
    price: 120,
    categoryId: '5',
    images: ['https://images.unsplash.com/photo-1581004710319-b93316e476e1?w=400'],
    stock: 70,
    unit: 'pack',
    weight: 0.5,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '22',
    vendorId: '10',
    name: 'Multivitamin Capsules',
    description: 'Complete multivitamin capsule with minerals',
    price: 450,
    categoryId: '4',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400'],
    stock: 55,
    unit: 'pack',
    weight: 0.05,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '23',
    vendorId: '1',
    name: 'Mangoes (Alphonso)',
    description: 'Premium Alphonso mangoes from Ratnagiri',
    price: 400,
    categoryId: '3',
    images: ['https://images.unsplash.com/photo-1553279903-fcc6c9a8e5d9?w=400'],
    stock: 25,
    unit: 'kg',
    weight: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '24',
    vendorId: '2',
    name: 'Broccoli',
    description: 'Fresh organic broccoli, packed with nutrients',
    price: 80,
    categoryId: '2',
    images: ['https://images.unsplash.com/photo-1518843875959-a57870e5f7bd?w=400'],
    stock: 40,
    unit: 'kg',
    weight: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '25',
    vendorId: '3',
    name: 'Digestive Tablets',
    description: 'Antacid tablets for acidity and heartburn relief',
    price: 45,
    categoryId: '4',
    images: ['https://images.unsplash.com/photo-1598204817638-75d5bed0e331?w=400'],
    stock: 200,
    unit: 'pack',
    weight: 0.05,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
]

// Mock Customers
export const mockCustomers = [
  {
    id: 'customer1',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@example.com',
    phone: '+91-9876543210',
    address: {
      id: 'addr1',
      label: 'Home',
      addressLine1: '101 MG Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      postalCode: '400001',
      country: 'India',
      latitude: 19.0760,
      longitude: 72.8777,
    },
    loyaltyTier: 'Gold',
    loyaltyPoints: 1250,
    totalSpent: 25000,
    ordersCount: 42,
    lastOrderDate: '2024-12-25',
    registeredDate: '2023-05-15',
    isActive: true,
    preferredCategories: ['Fruits', 'Vegetables', 'Dairy'],
    paymentMethods: ['upi', 'card'],
    profilePicture: 'https://api.dicebear.com/7.x/personas/svg?seed=rahul',
  },
  {
    id: 'customer2',
    name: 'Priya Patel',
    email: 'priya.patel@example.com',
    phone: '+91-9876543211',
    address: {
      id: 'addr2',
      label: 'Apartment',
      addressLine1: '202 Park View',
      city: 'Ahmedabad',
      state: 'Gujarat',
      postalCode: '380001',
      country: 'India',
      latitude: 23.0225,
      longitude: 72.5714,
    },
    loyaltyTier: 'Platinum',
    loyaltyPoints: 2800,
    totalSpent: 48000,
    ordersCount: 78,
    lastOrderDate: '2024-12-26',
    registeredDate: '2022-11-20',
    isActive: true,
    preferredCategories: ['Electronics', 'Pharmacy', 'Groceries'],
    paymentMethods: ['upi', 'wallet'],
    profilePicture: 'https://api.dicebear.com/7.x/personas/svg?seed=priya',
  },
  {
    id: 'customer3',
    name: 'Amit Kumar',
    email: 'amit.kumar@example.com',
    phone: '+91-9876543212',
    address: {
      id: 'addr3',
      label: 'Office',
      addressLine1: '303 Business Tower',
      city: 'Bangalore',
      state: 'Karnataka',
      postalCode: '560001',
      country: 'India',
      latitude: 12.9716,
      longitude: 77.5946,
    },
    loyaltyTier: 'Silver',
    loyaltyPoints: 650,
    totalSpent: 12000,
    ordersCount: 25,
    lastOrderDate: '2024-12-24',
    registeredDate: '2024-02-10',
    isActive: true,
    preferredCategories: ['Electronics', 'Bakery'],
    paymentMethods: ['card', 'cod'],
    profilePicture: 'https://api.dicebear.com/7.x/personas/svg?seed=amit',
  },
  {
    id: 'customer4',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@example.com',
    phone: '+91-9876543213',
    address: {
      id: 'addr4',
      label: 'Residence',
      addressLine1: '404 Hillside Villa',
      city: 'Hyderabad',
      state: 'Telangana',
      postalCode: '500001',
      country: 'India',
      latitude: 17.3850,
      longitude: 78.4867,
    },
    loyaltyTier: 'Gold',
    loyaltyPoints: 1800,
    totalSpent: 32000,
    ordersCount: 56,
    lastOrderDate: '2024-12-26',
    registeredDate: '2023-08-05',
    isActive: true,
    preferredCategories: ['Fruits', 'Vegetables', 'Medicines'],
    paymentMethods: ['upi', 'card'],
    profilePicture: 'https://api.dicebear.com/7.x/personas/svg?seed=sneha',
  },
  {
    id: 'customer5',
    name: 'Vikram Singh',
    email: 'vikram.singh@example.com',
    phone: '+91-9876543214',
    address: {
      id: 'addr5',
      label: 'House',
      addressLine1: '505 Heritage Lane',
      city: 'Delhi',
      state: 'Delhi',
      postalCode: '110001',
      country: 'India',
      latitude: 28.7041,
      longitude: 77.1025,
    },
    loyaltyTier: 'Bronze',
    loyaltyPoints: 320,
    totalSpent: 8500,
    ordersCount: 18,
    lastOrderDate: '2024-12-20',
    registeredDate: '2024-01-15',
    isActive: true,
    preferredCategories: ['Electronics', 'Groceries'],
    paymentMethods: ['card', 'upi'],
    profilePicture: 'https://api.dicebear.com/7.x/personas/svg?seed=vikram',
  },
  {
    id: 'customer6',
    name: 'Ananya Nair',
    email: 'ananya.nair@example.com',
    phone: '+91-9876543215',
    address: {
      id: 'addr6',
      label: 'Condo',
      addressLine1: '606 Sea View',
      city: 'Chennai',
      state: 'Tamil Nadu',
      postalCode: '600001',
      country: 'India',
      latitude: 13.0827,
      longitude: 80.2707,
    },
    loyaltyTier: 'Platinum',
    loyaltyPoints: 3500,
    totalSpent: 65000,
    ordersCount: 95,
    lastOrderDate: '2024-12-25',
    registeredDate: '2022-07-12',
    isActive: true,
    preferredCategories: ['Fruits', 'Dairy', 'Bakery'],
    paymentMethods: ['upi', 'wallet'],
    profilePicture: 'https://api.dicebear.com/7.x/personas/svg?seed=ananya',
  },
  {
    id: 'customer7',
    name: 'Rajesh Gupta',
    email: 'rajesh.gupta@example.com',
    phone: '+91-9876543216',
    address: {
      id: 'addr7',
      label: 'Flat',
      addressLine1: '707 Garden Complex',
      city: 'Pune',
      state: 'Maharashtra',
      postalCode: '411001',
      country: 'India',
      latitude: 18.5204,
      longitude: 73.8567,
    },
    loyaltyTier: 'Silver',
    loyaltyPoints: 950,
    totalSpent: 18000,
    ordersCount: 34,
    lastOrderDate: '2024-12-22',
    registeredDate: '2023-11-08',
    isActive: true,
    preferredCategories: ['Medicines', 'Groceries'],
    paymentMethods: ['card', 'cod'],
    profilePicture: 'https://api.dicebear.com/7.x/personas/svg?seed=rajesh',
  },
  {
    id: 'customer8',
    name: 'Kavita Menon',
    email: 'kavita.menon@example.com',
    phone: '+91-9876543217',
    address: {
      id: 'addr8',
      label: 'Bungalow',
      addressLine1: '808 Lakeside Drive',
      city: 'Kochi',
      state: 'Kerala',
      postalCode: '682001',
      country: 'India',
      latitude: 9.9312,
      longitude: 76.2683,
    },
    loyaltyTier: 'Gold',
    loyaltyPoints: 2100,
    totalSpent: 38000,
    ordersCount: 67,
    lastOrderDate: '2024-12-26',
    registeredDate: '2023-03-22',
    isActive: true,
    preferredCategories: ['Fruits', 'Vegetables', 'Dairy'],
    paymentMethods: ['upi', 'card'],
    profilePicture: 'https://api.dicebear.com/7.x/personas/svg?seed=kavita',
  },
  {
    id: 'customer9',
    name: 'Arjun Verma',
    email: 'arjun.verma@example.com',
    phone: '+91-9876543218',
    address: {
      id: 'addr9',
      label: 'Residency',
      addressLine1: '909 Skyline Heights',
      city: 'Jaipur',
      state: 'Rajasthan',
      postalCode: '302001',
      country: 'India',
      latitude: 26.9124,
      longitude: 75.7873,
    },
    loyaltyTier: 'Bronze',
    loyaltyPoints: 450,
    totalSpent: 9500,
    ordersCount: 22,
    lastOrderDate: '2024-12-23',
    registeredDate: '2024-04-18',
    isActive: true,
    preferredCategories: ['Electronics', 'Meat & Fish'],
    paymentMethods: ['card', 'upi'],
    profilePicture: 'https://api.dicebear.com/7.x/personas/svg?seed=arjun',
  },
  {
    id: 'customer10',
    name: 'Meera Iyer',
    email: 'meera.iyer@example.com',
    phone: '+91-9876543219',
    address: {
      id: 'addr10',
      label: 'Home',
      addressLine1: '1010 Riverside Colony',
      city: 'Surat',
      state: 'Gujarat',
      postalCode: '395001',
      country: 'India',
      latitude: 21.1702,
      longitude: 72.8311,
    },
    loyaltyTier: 'Platinum',
    loyaltyPoints: 4200,
    totalSpent: 78000,
    ordersCount: 125,
    lastOrderDate: '2024-12-26',
    registeredDate: '2022-09-30',
    isActive: true,
    preferredCategories: ['Groceries', 'Pharmacy', 'Bakery'],
    paymentMethods: ['upi', 'wallet'],
    profilePicture: 'https://api.dicebear.com/7.x/personas/svg?seed=meera',
  },
  {
    id: 'customer11',
    name: 'Sanjay Joshi',
    email: 'sanjay.joshi@example.com',
    phone: '+91-9876543220',
    address: {
      id: 'addr11',
      label: 'Apartment',
      addressLine1: '1111 Heritage Towers',
      city: 'Lucknow',
      state: 'Uttar Pradesh',
      postalCode: '226001',
      country: 'India',
      latitude: 26.8467,
      longitude: 80.9462,
    },
    loyaltyTier: 'Gold',
    loyaltyPoints: 1650,
    totalSpent: 29500,
    ordersCount: 48,
    lastOrderDate: '2024-12-21',
    registeredDate: '2023-06-14',
    isActive: true,
    preferredCategories: ['Fruits', 'Dairy', 'Electronics'],
    paymentMethods: ['card', 'cod'],
    profilePicture: 'https://api.dicebear.com/7.x/personas/svg?seed=sanjay',
  },
  {
    id: 'customer12',
    name: 'Pooja Agarwal',
    email: 'pooja.agarwal@example.com',
    phone: '+91-9876543221',
    address: {
      id: 'addr12',
      label: 'Villa',
      addressLine1: '1212 Premium Enclave',
      city: 'Nagpur',
      state: 'Maharashtra',
      postalCode: '440001',
      country: 'India',
      latitude: 21.1458,
      longitude: 79.0882,
    },
    loyaltyTier: 'Silver',
    loyaltyPoints: 780,
    totalSpent: 15200,
    ordersCount: 29,
    lastOrderDate: '2024-12-24',
    registeredDate: '2023-12-03',
    isActive: true,
    preferredCategories: ['Medicines', 'Groceries', 'Bakery'],
    paymentMethods: ['upi', 'card'],
    profilePicture: 'https://api.dicebear.com/7.x/personas/svg?seed=pooja',
  },
  {
    id: 'customer13',
    name: 'Deepak Malhotra',
    email: 'deepak.malhotra@example.com',
    phone: '+91-9876543222',
    address: {
      id: 'addr13',
      label: 'Residential',
      addressLine1: '1313 Corporate Avenue',
      city: 'Indore',
      state: 'Madhya Pradesh',
      postalCode: '452001',
      country: 'India',
      latitude: 22.7206,
      longitude: 75.8634,
    },
    loyaltyTier: 'Bronze',
    loyaltyPoints: 280,
    totalSpent: 7200,
    ordersCount: 15,
    lastOrderDate: '2024-12-19',
    registeredDate: '2024-03-07',
    isActive: true,
    preferredCategories: ['Electronics', 'Meat & Fish'],
    paymentMethods: ['card', 'upi'],
    profilePicture: 'https://api.dicebear.com/7.x/personas/svg?seed=deepak',
  },
  {
    id: 'customer14',
    name: 'Shruti Shah',
    email: 'shruti.shah@example.com',
    phone: '+91-9876543223',
    address: {
      id: 'addr14',
      label: 'Townhouse',
      addressLine1: '1414 Heritage Street',
      city: 'Vadodara',
      state: 'Gujarat',
      postalCode: '390001',
      country: 'India',
      latitude: 22.3072,
      longitude: 73.1812,
    },
    loyaltyTier: 'Gold',
    loyaltyPoints: 2300,
    totalSpent: 41000,
    ordersCount: 63,
    lastOrderDate: '2024-12-26',
    registeredDate: '2023-01-25',
    isActive: true,
    preferredCategories: ['Fruits', 'Vegetables', 'Dairy'],
    paymentMethods: ['upi', 'wallet'],
    profilePicture: 'https://api.dicebear.com/7.x/personas/svg?seed=shruti',
  },
  {
    id: 'customer15',
    name: 'Nikhil Rao',
    email: 'nikhil.rao@example.com',
    phone: '+91-9876543224',
    address: {
      id: 'addr15',
      label: 'Duplex',
      addressLine1: '1515 Garden Estate',
      city: 'Coimbatore',
      state: 'Tamil Nadu',
      postalCode: '641001',
      country: 'India',
      latitude: 11.0168,
      longitude: 76.9558,
    },
    loyaltyTier: 'Platinum',
    loyaltyPoints: 3800,
    totalSpent: 72000,
    ordersCount: 110,
    lastOrderDate: '2024-12-25',
    registeredDate: '2022-10-17',
    isActive: true,
    preferredCategories: ['Electronics', 'Pharmacy', 'Groceries'],
    paymentMethods: ['card', 'upi'],
    profilePicture: 'https://api.dicebear.com/7.x/personas/svg?seed=nikhil',
  }
];
